kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alertmananger-bot
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m

    receivers:
    - name: alertmananger-bot
      webhook_configs:
      - send_resolved: true
        url: 'http://alertmanager-bot:8080'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
spec:
  serviceName: alertmanager
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.19.0
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: templates-volume
        configMap:
          name: alertmanager-templates
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: alertmanager-bot
  name: alertmanager-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-bot
  serviceName: alertmanager-bot
  template:
    metadata:
      labels:
        app: alertmanager-bot
      name: alertmanager-bot
    spec:
      containers:
      - args:
        - --alertmanager.url=http://alertmanager:9093
        - --log.level=info
        - --store=bolt
        - --bolt.path=/data/bot.db
        env:
        - name: TELEGRAM_ADMIN
          valueFrom:
            secretKeyRef:
              key: admin
              name: alertmanager-bot
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: alertmanager-bot
        image: metalmatze/alertmanager-bot:0.4.3
        imagePullPolicy: IfNotPresent
        name: alertmanager-bot
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /data
          name: alertmanager-bot
      restartPolicy: Always
      volumes:
      - name: alertmanager-bot
        persistentVolumeClaim:
          claimName: alertmanager-bot
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-bot
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: alertmanager-bot