name: linting
on:
  push:
    branches:
      - master
    tags:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis)
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Format.
        run: make format

      - name: Linting & vetting.
        run: make lint